[package]
name = "gob_ion"
version = "0.1.0"
authors = ["storyfeet <thebeaky@psmail.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gobble={path="../../mlibs/gobble/"}
err_tools={path="../../mlibs/err_tools/"}
anyhow = "1.0.34"
glob = "0.3.0"
